version: 2.1

commands:
  notify_slack_failure:
    steps:
      - run:
          name: Notify Slack of failure if on master
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":boom: ${CIRCLE_JOB} failed: ${CIRCLE_BUILD_URL}\"}" https://hooks.slack.com/services/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
            fi
          when: on_fail

docker: &DOCKER_NODE
  docker:
    - image: circleci/node:10.17

jobs:
  install:
    <<: *DOCKER_NODE
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - notify_slack_failure

  build:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm ls
      - run: npm run build
      - run: npm run build:storybook
      - persist_to_workspace:
          root: ~/
          paths:
            - project/pkg
            - project/storybook-static
      - notify_slack_failure

  unit:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test
      - notify_slack_failure

  lint:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint

  deploy:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run deploy -- --existing-output-dir=~/project/storybook-static --ci
      - notify_slack_failure

  release:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npx semantic-release
      - notify_slack_failure

workflows:
  version: 2
  test:
    jobs:
      - install

      - build:
          requires:
            - install

      - unit:
          requires:
            - install

      - lint:
          requires:
            - install

      - deploy:
          requires:
            - unit
            - build
          filters:
            branches:
              only: master

      - release:
          requires:
            - lint
            - unit
            - build
          filters:
            branches:
              only: master
