version: 2.1

docker: &DOCKER_NODE
  docker:
    - image: circleci/node:10.16

jobs:
  install:
    <<: *DOCKER_NODE
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  build:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm ls
      - run: npm run build
      - run: npm run build:storybook
      - persist_to_workspace:
          root: ~/project
          paths:
            - storybook-static

  unit:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test

  lint:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint

  deploy:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run deploy -- --existing-output-dir=~/project/storybook-static

workflows:
  version: 2
  test:
    jobs:
      - install

      - build:
          requires:
            - install

      - unit:
          requires:
            - install

      - lint:
          requires:
            - install

      - deploy:
          requires:
            - unit
            - build
          # filters:
          #   branches:
          #     only: master
