version: 2.1

orbs:
  slack: circleci/slack@3.4.1

docker: &DOCKER_NODE
  docker:
    - image: circleci/node:10.19

jobs:
  install:
    <<: *DOCKER_NODE
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - slack/notify-on-failure

  build:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm ls
      - run: npm run build
      - run: npm run build:storybook
      - persist_to_workspace:
          root: ~/
          paths:
            - project/pkg
            - project/storybook-static
      - slack/notify-on-failure

  unit:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test
      - slack/notify-on-failure

  lint:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint

  deploy:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run deploy -- --existing-output-dir=~/project/storybook-static --ci
      - slack/notify-on-failure

  release:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npx semantic-release
      - slack/notify-on-failure

  pre_release:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      # manually set PR shell variables to empty to build pull request
      - run: CI_PULL_REQUEST= CIRCLE_PULL_REQUEST= npx semantic-release
      - slack/notify-on-failure

workflows:
  version: 2
  test:
    jobs:
      - install

      - build:
          requires:
            - install

      - unit:
          requires:
            - install

      - lint:
          requires:
            - install

      - deploy:
          requires:
            - unit
            - build
          filters:
            branches:
              only: master

      - release:
          requires:
            - lint
            - unit
            - build
          filters:
            branches:
              only: master

      - pre_release:
          requires:
            - lint
            - unit
            - build
          filters:
            branches:
              ignore: master
