version: 2.1

orbs:
  slack: circleci/slack@3.4.2

docker: &DOCKER_NODE
  docker:
    - image: cimg/node:16.15.0

bob_the_builder: &BOB_THE_BUILDER
  docker:
    - image: 309103291696.dkr.ecr.eu-central-1.amazonaws.com/platform/bob-the-builder:master

  environment:
    AWS_DEFAULT_REGION: eu-central-1
    DOCKER_REPOSITORY: 309103291696.dkr.ecr.eu-central-1.amazonaws.com
    DOCKER_NAMESPACE: frontend

jobs:
  install:
    <<: *DOCKER_NODE
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - slack/notify-on-failure:
          only_for_branches: master

  build:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm ls
      - run: npm run build
      - run: npm run build:storybook
      - run: npm run bundlesize
      - persist_to_workspace:
          root: ~/
          paths:
            - project/pkg
            - project/src/assets/dist
            - project/storybook-static
      - slack/notify-on-failure:
          only_for_branches: master

  unit:
    <<: *DOCKER_NODE
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test -- --maxWorkers=4
      - slack/notify-on-failure:
          only_for_branches: master

  lint:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint

  typecheck:
    <<: *DOCKER_NODE
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: npm run typecheck
          no_output_timeout: 1m
      - slack/notify-on-failure:
          only_for_branches: master

  release:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      - run: npx semantic-release
      - slack/notify-on-failure:
          only_for_branches: master

  pre_release:
    <<: *DOCKER_NODE
    steps:
      - attach_workspace:
          at: ~/
      # manually set PR shell variables to empty to build pull request
      - run: CI_PULL_REQUEST= CIRCLE_PULL_REQUEST= npx semantic-release
      - slack/notify-on-failure:
          only_for_branches: master

  docker_build:
    <<: *BOB_THE_BUILDER
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run: /build/build.sh
      - run: /push/push.sh
      - slack/notify-on-failure:
          only_for_branches: master

  deploy_branch:
    <<: *BOB_THE_BUILDER
    resource_class: small
    steps:
      - checkout
      - run: STAGE_NAME=branch /deploy/deploy.sh
      - run: STAGE_NAME=branch /deploy/branch_deployment_url.sh > deployment-url
      - persist_to_workspace:
          root: ~/project
          paths:
            - deployment-url
      - slack/notify-on-failure:
          only_for_branches: master

workflows:
  version: 2
  test:
    jobs:
      - install

      - build:
          requires:
            - install

      - unit:
          requires:
            - build

      - lint:
          requires:
            - build

      - typecheck:
          requires:
            - build

      - release:
          requires:
            - lint
            - unit
            - build
            - typecheck
          filters:
            branches:
              only: master

      - pre_release:
          requires:
            - lint
            - unit
            - build
            - typecheck
          filters:
            branches:
              ignore: master

      - docker_build

      - deploy_branch:
          requires:
            - docker_build
