{{- if not .Values.ingress.basic_auth_external_secret }}

apiVersion: v1
data:
  auth: {{ .Values.ingress.basic_auth_users }}
kind: Secret
metadata:
  name: carforyou-components-pkg-basic-auth
  namespace: {{ .Values.namespace }}
type: Opaque

{{- end }}
