name: Semantic Release

on: 
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest  
    steps:
    - name: Semantic Release Action
      uses: codfish/semantic-release-action@v1
